### ISSUE TITLE
wsl-config.scm:39:0: error: glibc-2.31: unbound variable

### ISSUE THREAD

**Issue by vitaliel** [giuliano108/guix-packages#12] opened 2022-08-18 22:51 UTC
```
# guix system reconfigure --no-bootloader wsl-config.scm
/root/wsl-config.scm:39:0: error: glibc-2.31: unbound variable
hint: Did you forget a `use-modules' form?
```

I removed `glibc-2.31` and it started

**Comment by giuliano108** [comment] 2022-09-10 22:58
Hi @vitaliel, I cannot reproduce the issue on a fresh install.

Current user profile, showing that no packages are installed, guix version:
```
bash-5.1# echo $GUIX_PROFILE
/root/.guix-profile
bash-5.1# guix package -I
bash-5.1# guix system list-generations
Generation 1    Sep 10 2022 23:31:58    (current)
  file name: /var/guix/profiles/system-1-link
  canonical file name: /gnu/store/jyzzq13k35m67i1pghyf3wimrvqzl35y-system
  label: GNU with Hello 2.12.1
  bootloader: dummybootloader
  root device: /dev/sdb
  kernel: /gnu/store/s5pd3rnzymliafb4la5sca63j86xs0y0-hello-2.12.1/bzImage
  channels:
    guix:
      repository URL: https://git.savannah.gnu.org/git/guix.git
      branch: master
      commit: 6ee40c3d9970cbedfbaf078e93ac2440cc3416f1
  configuration file: /gnu/store/z469yywbvq9bk88in88572gmxhr5v5jz-configuration.scm
bash-5.1#
```

Those `glibc` packages come from `(use-service-modules base)`, they do exist on my setup...

```
bash-5.1# guix repl
GNU Guile 3.0.8
Copyright (C) 1995-2021 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guix-user)> (use-modules
  (gnu)
  (gnu system linux-container)
  (gnu services shepherd)
  (guix profiles)
  (guix packages)
  (srfi srfi-1))
scheme@(guix-user)> (use-service-modules base)
scheme@(guix-user)> glibc
$1 = #<package glibc@2.33 gnu/packages/base.scm:695 7f67d7a104d0>
scheme@(guix-user)> glibc-2.29
$2 = #<package glibc@2.29 gnu/packages/base.scm:1052 7f67d7a100b0>
scheme@(guix-user)> glibc-2.31
$3 = #<package glibc@2.31 gnu/packages/base.scm:989 7f67d7a10370>
scheme@(guix-user)>
bash-5.1#
```

I'll close the issue as it looks like you've solved your problem and I can't reproduce it...

**Closed as completed by giuliano108** 2022-09-10 22:58 UTC
